import { getLanguage } from '../utils/translations';

// Tutorial text for games 5-36, translated into all 6 supported languages.
// Games 1-4 use translation keys directly in translations.jsx (gameXTutorialY).
const tutorialContent = {
  5: {
    objective: {
      en: "Find and click the item that is different from the rest. One shape or color will stand out - that's your target!",
      es: "Encuentra y haz clic en el elemento diferente a los demás. Una forma o color destacará - ¡ese es tu objetivo!",
      fr: "Trouvez et cliquez sur l'élément différent des autres. Une forme ou couleur se démarquera - c'est votre cible !",
      de: "Finde und klicke auf das Element, das sich von den anderen unterscheidet. Eine Form oder Farbe sticht heraus - das ist dein Ziel!",
      hu: "Keresd meg és kattints arra az elemre, amelyik különbözik a többitől. Egy alak vagy szín ki fog tűnni - az a célod!",
      ar: "ابحث وانقر على العنصر المختلف عن البقية. سيبرز شكل أو لون واحد - هذا هو هدفك!",
    },
    controls: {
      en: "Click or tap on the item you think is different. Work quickly but carefully - wrong answers deduct points!",
      es: "Haz clic o toca el elemento que creas diferente. ¡Trabaja rápido pero con cuidado - las respuestas incorrectas restan puntos!",
      fr: "Cliquez ou tapez sur l'élément que vous pensez être différent. Allez vite mais avec soin - les mauvaises réponses font perdre des points !",
      de: "Klicke oder tippe auf das Element, das du für unterschiedlich hältst. Sei schnell aber vorsichtig - falsche Antworten kosten Punkte!",
      hu: "Kattints vagy koppints arra az elemre, amelyet másnak gondolsz. Dolgozz gyorsan, de óvatosan - a hibás válaszok pontokat vonnak le!",
      ar: "انقر أو المس العنصر الذي تعتقد أنه مختلف. اعمل بسرعة ولكن بعناية - الإجابات الخاطئة تخصم نقاطًا!",
    },
    tips: {
      en: "Scan the grid systematically. Look for differences in shape OR color. The odd one out becomes more subtle at higher difficulties!",
      es: "Escanea la cuadrícula sistemáticamente. Busca diferencias de forma O color. ¡El elemento diferente se vuelve más sutil en dificultades altas!",
      fr: "Parcourez la grille systématiquement. Cherchez les différences de forme OU de couleur. L'intrus devient plus subtil aux difficultés supérieures !",
      de: "Untersuche das Raster systematisch. Suche nach Form- ODER Farbunterschieden. Der Außenseiter wird bei höheren Schwierigkeiten subtiler!",
      hu: "Vizsgáld át a rácsot szisztematikusan. Keresd az alak- VAGY színbeli különbségeket. A kiváló elem magasabb nehézségeknél finomabb lesz!",
      ar: "امسح الشبكة بشكل منهجي. ابحث عن الاختلافات في الشكل أو اللون. يصبح العنصر المختلف أكثر دقة في المستويات الأعلى!",
    },
  },
  6: {
    objective: {
      en: "Memorize number sequences that appear briefly, then type them back correctly. Sequences get longer as you progress!",
      es: "Memoriza secuencias de números que aparecen brevemente, luego escríbelas correctamente. ¡Las secuencias se alargan a medida que avanzas!",
      fr: "Mémorisez les séquences de nombres qui apparaissent brièvement, puis tapez-les correctement. Les séquences s'allongent au fur et à mesure !",
      de: "Merke dir kurz erscheinende Zahlenreihen und tippe sie dann korrekt ein. Die Reihen werden mit dem Fortschritt länger!",
      hu: "Memorizáld a röviden megjelenő számsorokat, majd írd be őket helyesen. A sorozatok egyre hosszabbak lesznek, ahogy haladsz!",
      ar: "احفظ تسلسلات الأرقام التي تظهر لفترة وجيزة، ثم اكتبها بشكل صحيح. تطول التسلسلات كلما تقدمت!",
    },
    controls: {
      en: "Watch the numbers carefully when shown. Then type the exact sequence and press Enter or click Submit.",
      es: "Observa los números con atención cuando aparezcan. Luego escribe la secuencia exacta y presiona Enter o haz clic en Enviar.",
      fr: "Observez attentivement les nombres lorsqu'ils apparaissent. Tapez ensuite la séquence exacte et appuyez sur Entrée ou cliquez sur Valider.",
      de: "Beobachte die Zahlen sorgfältig, wenn sie gezeigt werden. Tippe dann die genaue Reihenfolge ein und drücke Enter oder klicke auf Senden.",
      hu: "Figyeld gondosan a számokat, amikor megjelennek. Ezután írd be a pontos sorozatot, és nyomj Entert vagy kattints a Küldésre.",
      ar: "راقب الأرقام بعناية عندما تظهر. ثم اكتب التسلسل بالضبط واضغط Enter أو انقر على إرسال.",
    },
    tips: {
      en: "Try chunking: group numbers mentally (like phone numbers). Focus hard during the display. Three mistakes ends the game!",
      es: "Prueba agrupar: junta los números mentalmente (como números de teléfono). ¡Concéntrate durante la visualización. Tres errores terminan el juego!",
      fr: "Essayez le regroupement : assemblez les nombres mentalement (comme des numéros de téléphone). Concentrez-vous pendant l'affichage. Trois erreurs terminent la partie !",
      de: "Versuche zu bündeln: gruppiere Zahlen gedanklich (wie Telefonnummern). Konzentriere dich stark beim Anzeigen. Drei Fehler beenden das Spiel!",
      hu: "Próbáld a csoportosítást: értelmezd össze a számokat (mint telefonszámokat). Koncentrálj erősen a megjelenítés alatt. Három hiba véget vet a játéknak!",
      ar: "جرب التقسيم: اجمع الأرقام ذهنيًا (مثل أرقام الهاتف). ركز بشدة أثناء العرض. ثلاثة أخطاء تنهي اللعبة!",
    },
  },
  9: {
    objective: {
      en: "A sequence of shapes (and colors) appears with a '?' at the end. Study the repeating pattern, then pick the item that comes next!",
      es: "Aparece una secuencia de formas (y colores) con un '?' al final. Estudia el patrón repetido, ¡luego elige el elemento que sigue!",
      fr: "Une séquence de formes (et couleurs) apparaît avec un '?' à la fin. Étudiez le motif répétitif, puis choisissez l'élément suivant !",
      de: "Eine Reihe von Formen (und Farben) erscheint mit einem '?' am Ende. Studiere das wiederholende Muster und wähle dann das nächste Element!",
      hu: "Egy alakokból (és színekből) álló sorozat jelenik meg egy '?'-rel a végén. Tanulmányozd az ismétlődő mintát, majd válaszd a következő elemet!",
      ar: "يظهر تسلسل من الأشكال (والألوان) مع علامة '?' في النهاية. ادرس النمط المتكرر، ثم اختر العنصر التالي!",
    },
    controls: {
      en: "Click an answer card or press the number key (1-4 or 1-6) shown on each option. Correct answers score points; wrong ones lose points!",
      es: "Haz clic en una tarjeta de respuesta o presiona la tecla numérica (1-4 o 1-6) que se muestra en cada opción. ¡Respuestas correctas suman puntos; las incorrectas los restan!",
      fr: "Cliquez sur une carte de réponse ou appuyez sur la touche numérique (1-4 ou 1-6) affichée sur chaque option. Les bonnes réponses marquent des points ; les mauvaises en font perdre !",
      de: "Klicke auf eine Antwortkarte oder drücke die Ziffertaste (1-4 oder 1-6), die auf jeder Option angezeigt wird. Richtige Antworten geben Punkte; falsche kosten welche!",
      hu: "Kattints egy válaszkártyára vagy nyomd meg a szám billentyűt (1-4 vagy 1-6), amely minden opciónál megjelenik. A helyes válaszok pontot adnak; a rosszak pontot vonnak le!",
      ar: "انقر على بطاقة إجابة أو اضغط على مفتاح الرقم (1-4 أو 1-6) الظاهر على كل خيار. الإجابات الصحيحة تمنح نقاطًا؛ والخاطئة تخصم نقاطًا!",
    },
    tips: {
      en: "Easy = shapes only. Medium adds colors. Hard/expert use longer patterns and tighter timers — spot the cycle length fast!",
      es: "Fácil = solo formas. El nivel medio añade colores. ¡Difícil/experto usa patrones más largos y menos tiempo — detecta la longitud del ciclo rápido!",
      fr: "Facile = formes seulement. Moyen ajoute les couleurs. Difficile/expert utilise des motifs plus longs et des chronos plus serrés — repérez vite la longueur du cycle !",
      de: "Leicht = nur Formen. Mittel fügt Farben hinzu. Schwer/Experte nutzt längere Muster und knappere Timer — erkenne die Zykluslänge schnell!",
      hu: "Könnyű = csak alakok. Közepes hozzáadja a színeket. Nehéz/szakértő hosszabb mintákat és szorosabb időzítőket használ — fedezd fel gyorsan a ciklus hosszát!",
      ar: "سهل = أشكال فقط. المتوسط يضيف الألوان. الصعب/الخبير يستخدم أنماطًا أطول ومؤقتات أضيق — اكتشف طول الدورة بسرعة!",
    },
  },
  10: {
    objective: {
      en: "A rule appears (e.g. 'Is it a CIRCLE?' or 'Is it RED?'). For each shape shown, decide if it matches the rule!",
      es: "Aparece una regla (p. ej. '¿Es un CÍRCULO?' o '¿Es ROJO?'). ¡Para cada forma mostrada, decide si coincide con la regla!",
      fr: "Une règle apparaît (ex. 'Est-ce un CERCLE ?' ou 'Est-ce ROUGE ?'). Pour chaque forme affichée, décidez si elle correspond à la règle !",
      de: "Eine Regel erscheint (z. B. 'Ist es ein KREIS?' oder 'Ist es ROT?'). Entscheide bei jeder gezeigten Form, ob sie zur Regel passt!",
      hu: "Egy szabály jelenik meg (pl. 'Kör ez?' vagy 'Piros?'). Minden megjelenített alaknál döntsd el, hogy megfelel-e a szabálynak!",
      ar: "تظهر قاعدة (مثل 'هل هو دائرة؟' أو 'هل هو أحمر؟'). لكل شكل يظهر، قرر ما إذا كان يطابق القاعدة!",
    },
    controls: {
      en: "Click ✓ Match if the shape fits the rule, or ✗ Pass if it doesn't. Decide fast — the clock is ticking!",
      es: "Haz clic en ✓ Coincide si la forma cumple la regla, o ✗ Pasar si no. ¡Decide rápido — el reloj corre!",
      fr: "Cliquez sur ✓ Correspond si la forme respecte la règle, ou ✗ Passer sinon. Décidez vite — le chronomètre tourne !",
      de: "Klicke ✓ Passt, wenn die Form zur Regel passt, oder ✗ Weiter, wenn nicht. Entscheide schnell — die Uhr tickt!",
      hu: "Kattints az ✓ Egyezik gombra, ha az alak megfelel a szabálynak, vagy a ✗ Tovább gombra, ha nem. Dönts gyorsan — az óra ketyeg!",
      ar: "انقر على ✓ مطابق إذا كان الشكل يناسب القاعدة، أو ✗ تجاوز إذا لم يكن. قرر بسرعة — الوقت ينفد!",
    },
    tips: {
      en: "Focus on the rule's attribute only (shape or color). Wrong answers lose points, so stay sharp as the speed climbs!",
      es: "Concéntrate solo en el atributo de la regla (forma o color). ¡Las respuestas incorrectas restan puntos, así que mantente alerta al aumentar la velocidad!",
      fr: "Concentrez-vous uniquement sur l'attribut de la règle (forme ou couleur). Les mauvaises réponses font perdre des points, restez vif à mesure que la vitesse augmente !",
      de: "Konzentriere dich nur auf das Attribut der Regel (Form oder Farbe). Falsche Antworten kosten Punkte, bleib scharf, wenn das Tempo steigt!",
      hu: "Csak a szabály attribútumára koncentrálj (alak vagy szín). A hibás válaszok pontokat vonnak le, így maradj éles, ahogy nő a sebesség!",
      ar: "ركز فقط على سمة القاعدة (الشكل أو اللون). الإجابات الخاطئة تخصم نقاطًا، لذا ابقَ متيقظًا مع زيادة السرعة!",
    },
  },
  11: {
    objective: {
      en: "A grid full of shapes appears — but exactly TWO are identical. Find and tap the matching pair!",
      es: "Aparece una cuadrícula llena de formas — pero exactamente DOS son idénticas. ¡Encuentra y toca la pareja coincidente!",
      fr: "Une grille pleine de formes apparaît — mais exactement DEUX sont identiques. Trouvez et tapez la paire correspondante !",
      de: "Ein Raster voller Formen erscheint — aber genau ZWEI sind identisch. Finde und tippe auf das passende Paar!",
      hu: "Egy alakokkal teli rács jelenik meg — de pontosan KETTŐ azonos. Keresd meg és koppints a párosra!",
      ar: "تظهر شبكة مليئة بالأشكال — لكن اثنين فقط متطابقان. ابحث وانقر على الزوج المتطابق!",
    },
    controls: {
      en: "Click one shape, then click its twin. Correct pairs score points; mismatched picks lose points.",
      es: "Haz clic en una forma, luego en su gemela. Las parejas correctas suman puntos; las equivocadas restan puntos.",
      fr: "Cliquez sur une forme, puis sur son jumeau. Les bonnes paires marquent des points ; les erreurs en font perdre.",
      de: "Klicke auf eine Form, dann auf ihren Zwilling. Richtige Paare geben Punkte; falsche Paare kosten welche.",
      hu: "Kattints egy alakra, majd a párjára. A helyes párosok pontot adnak; a téves választások pontot vonnak le.",
      ar: "انقر على شكل واحد، ثم انقر على توأمه. الأزواج الصحيحة تمنح نقاطًا؛ والأزواج الخاطئة تخصم نقاطًا.",
    },
    tips: {
      en: "Scan by shape first, then by color. Bigger grids and shorter timers at higher levels — trust your eyes!",
      es: "Escanea primero por forma, luego por color. ¡Cuadrículas más grandes y menos tiempo en niveles altos — confía en tus ojos!",
      fr: "Parcourez d'abord par forme, puis par couleur. Grilles plus grandes et chronos plus courts aux niveaux supérieurs — faites confiance à vos yeux !",
      de: "Scanne zuerst nach Form, dann nach Farbe. Größere Raster und kürzere Timer bei höheren Levels — vertraue deinen Augen!",
      hu: "Elsőként alak szerint vizsgáld, utána szín szerint. Nagyobb rácsok és rövidebb időzítők magasabb szinteken — bízz a szemeidben!",
      ar: "امسح أولاً حسب الشكل، ثم حسب اللون. شبكات أكبر ومؤقتات أقصر في المستويات الأعلى — ثق بعينيك!",
    },
  },
  12: {
    objective: {
      en: "A target shape is shown. A grid flashes briefly — count how many targets you see, then pick the right number!",
      es: "Se muestra una forma objetivo. Una cuadrícula parpadea brevemente — ¡cuenta cuántos objetivos ves y elige el número correcto!",
      fr: "Une forme cible est affichée. Une grille clignote brièvement — comptez combien de cibles vous voyez, puis choisissez le bon nombre !",
      de: "Eine Zielform wird gezeigt. Ein Raster blinkt kurz — zähle, wie viele Ziele du siehst, und wähle dann die richtige Zahl!",
      hu: "Egy célalak jelenik meg. Egy rács röviden felvillan — számold meg, hány célt látsz, majd válaszd a helyes számot!",
      ar: "يظهر شكل مستهدف. تومض شبكة لفترة وجيزة — احسب عدد الأهداف التي تراها، ثم اختر الرقم الصحيح!",
    },
    controls: {
      en: "Watch the grid during the flash, then click the number button with your count. Wrong guesses lose points!",
      es: "Observa la cuadrícula durante el destello, luego haz clic en el botón con tu conteo. ¡Las respuestas incorrectas restan puntos!",
      fr: "Observez la grille pendant le flash, puis cliquez sur le bouton avec votre compte. Les mauvaises réponses font perdre des points !",
      de: "Beobachte das Raster beim Blinken, dann klicke auf die Zahl mit deiner Zählung. Falsche Schätzungen kosten Punkte!",
      hu: "Figyeld a rácsot a villanás alatt, majd kattints a számgombra a számlálásoddal. A téves találgatások pontokat vonnak le!",
      ar: "راقب الشبكة أثناء الوميض، ثم انقر على زر الرقم بعددك. التخمينات الخاطئة تخصم نقاطًا!",
    },
    tips: {
      en: "Lock onto the target's shape AND color. Group items visually to count faster. Higher levels flash quicker!",
      es: "Fíjate en la forma Y color del objetivo. Agrupa elementos visualmente para contar más rápido. ¡Los niveles altos parpadean más rápido!",
      fr: "Verrouillez la forme ET la couleur de la cible. Groupez les éléments visuellement pour compter plus vite. Les niveaux supérieurs clignotent plus vite !",
      de: "Fokussiere Form UND Farbe des Ziels. Gruppiere Elemente visuell, um schneller zu zählen. Höhere Levels blinken schneller!",
      hu: "Zárd be a cél alakját ÉS színét. Csoportosítsd vizuálisan az elemeket a gyorsabb számláláshoz. A magasabb szintek gyorsabban villannak!",
      ar: "ثبّت على شكل ولون الهدف. جمّع العناصر بصريًا للعد بشكل أسرع. المستويات الأعلى تومض أسرع!",
    },
  },
  13: {
    objective: {
      en: "Two shapes appear — the previous one and the current one. Decide if they match by the rule!",
      es: "Aparecen dos formas — la anterior y la actual. ¡Decide si coinciden según la regla!",
      fr: "Deux formes apparaissent — la précédente et l'actuelle. Décidez si elles correspondent selon la règle !",
      de: "Zwei Formen erscheinen — die vorherige und die aktuelle. Entscheide, ob sie nach der Regel übereinstimmen!",
      hu: "Két alak jelenik meg — az előző és a jelenlegi. Döntsd el, hogy egyeznek-e a szabály szerint!",
      ar: "يظهر شكلان — السابق والحالي. قرر ما إذا كانا يتطابقان وفق القاعدة!",
    },
    controls: {
      en: "Click Match if they fit the rule, or Different if not. Be quick — the timer is running!",
      es: "Haz clic en Coincide si cumplen la regla, o en Diferente si no. ¡Rápido — el cronómetro corre!",
      fr: "Cliquez sur Correspond si elles respectent la règle, ou Différent sinon. Soyez rapide — le chronomètre tourne !",
      de: "Klicke auf Passst, wenn sie zur Regel passen, oder Unterschiedlich, wenn nicht. Sei schnell — der Timer läuft!",
      hu: "Kattints az Egyezik gombra, ha megfelel a szabálynak, vagy a Különböző gombra, ha nem. Légy gyors — az időzítő fut!",
      ar: "انقر على مطابق إذا كانا يناسبان القاعدة، أو مختلف إذا لم يكن. كن سريعًا — المؤقت يعمل!",
    },
    tips: {
      en: "Easy checks color, medium checks shape, hard checks either, expert checks both. Focus only on the rule's attribute!",
      es: "Fácil revisa color, medio revisa forma, difícil revisa cualquiera, experto revisa ambos. ¡Concéntrate solo en el atributo de la regla!",
      fr: "Facile vérifie la couleur, moyen vérifie la forme, difficile vérifie l'un ou l'autre, expert vérifie les deux. Concentrez-vous uniquement sur l'attribut de la règle !",
      de: "Leicht prüft Farbe, mittel prüft Form, schwer prüft entweder, Experte prüft beide. Konzentriere dich nur auf das Attribut der Regel!",
      hu: "A könnyű a színt ellenőrzi, a közepes az alakot, a nehéz valamelyiket, a szakértő mindkettőt. Csak a szabály attribútumára koncentrálj!",
      ar: "السهل يفحص اللون، المتوسط يفحص الشكل، الصعب يفحص أيًا منهما، الخبير يفحص كليهما. ركز فقط على سمة القاعدة!",
    },
  },
  14: {
    objective: {
      en: "Watch cells light up in a sequence, then repeat the exact same path by clicking them in order!",
      es: "Observa cómo se iluminan las celdas en secuencia, ¡luego repite el mismo camino haciendo clic en orden!",
      fr: "Regardez les cellules s'allumer en séquence, puis répétez le même chemin en cliquant dans l'ordre !",
      de: "Schau zu, wie Zellen nacheinander aufleuchten, dann wiederhole denselben Weg, indem du sie in Reihenfolge anklickst!",
      hu: "Figyeld, ahogy a cellák sorban felgyulladnak, majd ismételd meg ugyanazt az utat a sorrendbeli kattintással!",
      ar: "شاهد الخلايا تضيء في تسلسل، ثم كرر نفس المسار بالنقر عليها بالترتيب!",
    },
    controls: {
      en: "Click each cell in the order it lit up. One wrong tap restarts the round — stay focused!",
      es: "Haz clic en cada celda en el orden que se iluminó. Un toque incorrecto reinicia la ronda — ¡mantente concentrado!",
      fr: "Cliquez sur chaque cellule dans l'ordre où elle s'est allumée. Une erreur redémarre le tour — restez concentré !",
      de: "Klicke jede Zelle in der Reihenfolge, in der sie aufleuchtete. Ein falscher Tipp startet die Runde neu — bleib fokussiert!",
      hu: "Kattints minden cellára abban a sorrendben, ahogy felgyulladt. Egy rossz koppintás újraindítja a kört — maradj fókuszált!",
      ar: "انقر على كل خلية بالترتيب الذي أضاءت به. نقرة خاطئة واحدة تعيد الجولة — ابقَ مركزًا!",
    },
    tips: {
      en: "Mentally number the cells. Higher levels add longer sequences and bigger grids!",
      es: "Numera mentalmente las celdas. ¡Los niveles altos añaden secuencias más largas y cuadrículas más grandes!",
      fr: "Numérotez mentalement les cellules. Les niveaux supérieurs ajoutent des séquences plus longues et des grilles plus grandes !",
      de: "Nummeriere die Zellen gedanklich. Höhere Levels fügen längere Sequenzen und größere Raster hinzu!",
      hu: "Számozd meg fejben a cellákat. A magasabb szintek hosszabb sorozatokat és nagyobb rácsokat adnak hozzá!",
      ar: "رقم الخلايا ذهنيًا. المستويات الأعلى تضيف تسلسلات أطول وشبكات أكبر!",
    },
  },
  15: {
    objective: {
      en: "Shapes pop up across the grid. Tap ONLY the ones matching the target color before they vanish!",
      es: "Aparecen formas por toda la cuadrícula. ¡Toca SOLO las que coincidan con el color objetivo antes de que desaparezcan!",
      fr: "Des formes surgissent sur la grille. Tapez UNIQUEMENT celles correspondant à la couleur cible avant qu'elles ne disparaissent !",
      de: "Formen tauchen im Raster auf. Tippe NUR auf die, die zur Zielfarbe passen, bevor sie verschwinden!",
      hu: "Alakok bukkannak fel a rácson. Koppints CSAK azokra, amelyek megegyeznek a célszínnel, mielőtt eltűnnek!",
      ar: "تظهر أشكال في جميع أنحاء الشبكة. انقر فقط على المطابقة للون المستهدف قبل أن تختفي!",
    },
    controls: {
      en: "Click target-color shapes to score. Tapping wrong colors loses points. Don't let targets escape!",
      es: "Haz clic en las formas del color objetivo para sumar puntos. Tocar colores incorrectos resta puntos. ¡No dejes escapar los objetivos!",
      fr: "Cliquez sur les formes de la couleur cible pour marquer. Toucher les mauvaises couleurs fait perdre des points. Ne laissez pas les cibles s'échapper !",
      de: "Klicke auf Formen in der Zielfarbe, um Punkte zu erzielen. Falsche Farben zu tippen kostet Punkte. Lass keine Ziele entkommen!",
      hu: "Kattints a célszínű alakokra a pontszerzéshez. A rossz színekre koppintás pontokat von le. Ne hagyd elmenekülni a célokat!",
      ar: "انقر على الأشكال باللون المستهدف لتسجيل النقاط. النقر على ألوان خاطئة يخصم نقاطًا. لا تدع الأهداف تفلت!",
    },
    tips: {
      en: "Keep your eyes on the target color. Shapes disappear fast — react quickly but accurately!",
      es: "Mantén los ojos en el color objetivo. Las formas desaparecen rápido — ¡reacciona rápido pero con precisión!",
      fr: "Gardez les yeux sur la couleur cible. Les formes disparaissent vite — réagissez vite mais avec précision !",
      de: "Behalte die Zielfarbe im Blick. Formen verschwinden schnell — reagiere schnell aber präzise!",
      hu: "Tartsd a szemeidet a célszínen. Az alakok gyorsan eltűnnek — reagálj gyorsan, de pontosan!",
      ar: "ابقَ عينيك على اللون المستهدف. الأشكال تختفي بسرعة — تفاعل بسرعة ولكن بدقة!",
    },
  },
  16: {
    objective: {
      en: "A sequence of shapes flashes one at a time. Then tap them BACKWARDS — the last shape first!",
      es: "Una secuencia de formas parpadea una por una. ¡Luego tócalas AL REVÉS — la última primero!",
      fr: "Une séquence de formes clignote une par une. Tapez-les ensuite À L'ENVERS — la dernière en premier !",
      de: "Eine Reihe von Formen blinkt einzeln. Tippe sie dann RÜCKWÄRTS — die letzte Form zuerst!",
      hu: "Egy alaksorozat egyenként felvillan. Ezután koppints rájuk VISSZAFELÉ — az utolsó alakot először!",
      ar: "يومض تسلسل من الأشكال واحدًا تلو الآخر. ثم انقر عليها بالعكس — الشكل الأخير أولاً!",
    },
    controls: {
      en: "Use the four shape buttons to replay the sequence in reverse order. Mistakes restart the round!",
      es: "Usa los cuatro botones de formas para repetir la secuencia en orden inverso. ¡Los errores reinician la ronda!",
      fr: "Utilisez les quatre boutons de forme pour rejouer la séquence à l'envers. Les erreurs redémarrent le tour !",
      de: "Nutze die vier Form-Buttons, um die Sequenz in umgekehrter Reihenfolge wiederzugeben. Fehler starten die Runde neu!",
      hu: "Használd a négy alakgombot a sorozat visszafelé történő lejátszásához. A hibák újraindítják a kört!",
      ar: "استخدم أزرار الأشكال الأربعة لإعادة تشغيل التسلسل بالترتيب العكسي. الأخطاء تعيد الجولة!",
    },
    tips: {
      en: "Mentally reverse the list as you watch. Longer sequences at higher levels test your working memory!",
      es: "Invierte mentalmente la lista mientras observas. ¡Las secuencias más largas en niveles altos ponen a prueba tu memoria de trabajo!",
      fr: "Inversez mentalement la liste pendant que vous regardez. Les séquences plus longues aux niveaux supérieurs testent votre mémoire de travail !",
      de: "Kehre die Liste beim Zuschauen gedanklich um. Längere Sequenzen bei höheren Levels testen dein Arbeitsgedächtnis!",
      hu: "Fordítsd meg fejben a listát, miközben nézed. A hosszabb sorozatok magasabb szinteken a munkamemóriádat tesztelik!",
      ar: "اعكس القائمة ذهنيًا أثناء المشاهدة. التسلسلات الأطول في المستويات الأعلى تختبر ذاكرتك العاملة!",
    },
  },
  17: {
    objective: {
      en: "A target shape is shown. Find the ONE match hidden among distractors and tap it fast!",
      es: "Se muestra una forma objetivo. ¡Encuentra la ÚNICA coincidencia oculta entre distractores y tócala rápido!",
      fr: "Une forme cible est affichée. Trouvez l'UNIQUE correspondance cachée parmi les distracteurs et tapez-la vite !",
      de: "Eine Zielform wird gezeigt. Finde die EINE Übereinstimmung, die zwischen Ablenkungen versteckt ist, und tippe sie schnell!",
      hu: "Egy célalak jelenik meg. Keresd meg az EGYETLEN egyezést, amely elrejtőzött a zavaró elemek között, és koppints rá gyorsan!",
      ar: "يظهر شكل مستهدف. ابحث عن التطابق الوحيد المخفي بين المشتتات وانقر عليه بسرعة!",
    },
    controls: {
      en: "Click the shape that matches the target's shape AND color. Wrong taps lose points; the clock is ticking!",
      es: "Haz clic en la forma que coincida en forma Y color con el objetivo. ¡Los toques incorrectos restan puntos; el reloj corre!",
      fr: "Cliquez sur la forme qui correspond à la forme ET la couleur de la cible. Les mauvaises touches font perdre des points ; le chronomètre tourne !",
      de: "Klicke auf die Form, die in Form UND Farbe zum Ziel passt. Falsche Tipps kosten Punkte; die Uhr tickt!",
      hu: "Kattints arra az alakra, amelyik alakra ÉS színre is egyezik a céllal. A rossz koppintások pontokat vonnak le; az óra ketyeg!",
      ar: "انقر على الشكل الذي يطابق شكل ولون الهدف. النقرات الخاطئة تخصم نقاطًا؛ الوقت ينفد!",
    },
    tips: {
      en: "Scan systematically left-to-right. Bigger grids and shorter timers at higher levels — trust your eyes!",
      es: "Escanea sistemáticamente de izquierda a derecha. ¡Cuadrículas más grandes y menos tiempo en niveles altos — confía en tus ojos!",
      fr: "Parcourez systématiquement de gauche à droite. Grilles plus grandes et chronos plus courts aux niveaux supérieurs — faites confiance à vos yeux !",
      de: "Scanne systematisch von links nach rechts. Größere Raster und kürzere Timer bei höheren Levels — vertraue deinen Augen!",
      hu: "Vizsgáld szisztematikusan balról jobbra. Nagyobb rácsok és rövidebb időzítők magasabb szinteken — bízz a szemeidben!",
      ar: "امسح بشكل منهجي من اليسار إلى اليمين. شبكات أكبر ومؤقتات أقصر في المستويات الأعلى — ثق بعينيك!",
    },
  },
  18: {
    objective: {
      en: "A color word appears in an ink color. Pick the INK color — ignore what the word says!",
      es: "Aparece una palabra de color en un color de tinta. ¡Elige el color de la TINTA — ignora lo que dice la palabra!",
      fr: "Un mot de couleur apparaît dans une couleur d'encre. Choisissez la couleur de l'ENCRE — ignorez ce que dit le mot !",
      de: "Ein Farbwort erscheint in einer Tintenfarbe. Wähle die TINTENFARBE — ignoriere, was das Wort sagt!",
      hu: "Egy színszó jelenik meg egy tinta színben. Válaszd a TINTA színét — hagyd figyelmen kívül, amit a szó mond!",
      ar: "تظهر كلمة لون بلون حبر. اختر لون الحبر — تجاهل ما تقوله الكلمة!",
    },
    controls: {
      en: "Click the button matching the ink color, not the word. Conflict rises at higher levels!",
      es: "Haz clic en el botón que coincida con el color de tinta, no con la palabra. ¡El conflicto aumenta en niveles altos!",
      fr: "Cliquez sur le bouton correspondant à la couleur de l'encre, pas au mot. Le conflit augmente aux niveaux supérieurs !",
      de: "Klicke auf den Button, der zur Tintenfarbe passt, nicht zum Wort. Der Konflikt steigt bei höheren Levels!",
      hu: "Kattints a gombra, amely a tinta színének felel meg, nem a szónak. A konfliktus magasabb szinteken nő!",
      ar: "انقر على الزر المطابق للون الحبر، وليس الكلمة. يزيد التعارض في المستويات الأعلى!",
    },
    tips: {
      en: "Don't read — look at the color. Your brain wants to read the word; fight that instinct to win!",
      es: "No leas — mira el color. Tu cerebro quiere leer la palabra; ¡lucha contra ese instinto para ganar!",
      fr: "Ne lisez pas — regardez la couleur. Votre cerveau veut lire le mot ; combattez cet instinct pour gagner !",
      de: "Lies nicht — schau auf die Farbe. Dein Gehirn will das Wort lesen; kämpfe gegen diesen Instinkt, um zu gewinnen!",
      hu: "Ne olvasd — nézd a színt. Az agyad olvasni akarja a szót; küzdj meg ezzel az ösztönnel a győzelemért!",
      ar: "لا تقرأ — انظر إلى اللون. عقلك يريد قراءة الكلمة؛ قاوم هذه الغريزة لتفوز!",
    },
  },
  19: {
    objective: {
      en: "Wait for the dot, then tap it as fast as you can! Don't tap too early.",
      es: "Espera el punto, ¡luego tócalo lo más rápido posible! No toques demasiado pronto.",
      fr: "Attendez le point, puis tapez-le le plus vite possible ! Ne tapez pas trop tôt.",
      de: "Warte auf den Punkt, dann tippe so schnell du kannst! Tippe nicht zu früh.",
      hu: "Várd a pontot, majd koppints rá a lehető leggyorsabban! Ne koppints túl korán.",
      ar: "انتظر النقطة، ثم انقر عليها بأسرع ما يمكن! لا تنقر مبكرًا جدًا.",
    },
    controls: {
      en: "Click anywhere when the dot appears. Tapping during the wait counts as a miss.",
      es: "Haz clic en cualquier lugar cuando aparezca el punto. Tocar durante la espera cuenta como fallo.",
      fr: "Cliquez n'importe où quand le point apparaît. Taper pendant l'attente compte comme un échec.",
      de: "Klicke irgendwo, wenn der Punkt erscheint. Tippen während des Wartens zählt als Fehlversuch.",
      hu: "Kattints bárhova, amikor a pont megjelenik. A várakozás alatti koppintás hibának számít.",
      ar: "انقر في أي مكان عندما تظهر النقطة. النقر أثناء الانتظار يعتبر خطأ.",
    },
    tips: {
      en: "Keep your finger ready but resist the urge to tap early. Faster taps = more points!",
      es: "Mantén el dedo listo pero resiste la tentación de tocar pronto. ¡Toques más rápidos = más puntos!",
      fr: "Gardez le doigt prêt mais résistez à l'envie de taper trop tôt. Tapes plus rapides = plus de points !",
      de: "Halte den Finger bereit, aber widerstehe dem Drang, zu früh zu tippen. Schnellere Tipps = mehr Punkte!",
      hu: "Tartsd készen az ujjad, de állj ellen a korai koppintás kísértésének. Gyorsabb koppintások = több pont!",
      ar: "ابقَ إصبعك جاهزًا لكن قاوم الرغبة في النقر مبكرًا. نقرات أسرع = نقاط أكثر!",
    },
  },
  20: {
    objective: {
      en: "Targets pop up one at a time — tap as many as you can before time runs out!",
      es: "Los objetivos aparecen de uno en uno — ¡toca todos los que puedas antes de que se acabe el tiempo!",
      fr: "Les cibles apparaissent une par une — tapez-en autant que possible avant la fin du temps !",
      de: "Ziele erscheinen einzeln — tippe so viele wie möglich, bevor die Zeit abläuft!",
      hu: "A célok egyenként bukkannak fel — koppints annyira, amennyire csak tudsz, mielőtt lejár az idő!",
      ar: "تظهر الأهداف واحدًا تلو الآخر — انقر على أكبر عدد ممكن قبل انتهاء الوقت!",
    },
    controls: {
      en: "Click each dot the instant it appears. Every tap scores points.",
      es: "Haz clic en cada punto en cuanto aparezca. Cada toque suma puntos.",
      fr: "Cliquez sur chaque point dès qu'il apparaît. Chaque tape marque des points.",
      de: "Klicke jeden Punkt sofort, wenn er erscheint. Jeder Tipp gibt Punkte.",
      hu: "Kattints minden pontra, amint megjelenik. Minden koppintás pontot ér.",
      ar: "انقر على كل نقطة بمجرد ظهورها. كل نقرة تمنح نقاطًا.",
    },
    tips: {
      en: "Stay alert and keep tapping — accuracy comes from speed at higher levels!",
      es: "Mantente alerta y sigue tocando — ¡la precisión viene de la velocidad en niveles altos!",
      fr: "Restez vigilant et continuez à taper — la précision vient de la vitesse aux niveaux supérieurs !",
      de: "Bleib aufmerksam und tippe weiter — Genauigkeit kommt durch Tempo bei höheren Levels!",
      hu: "Maradj éber és koppints tovább — a pontosság a sebességből jön magasabb szinteken!",
      ar: "ابقَ متيقظًا واستمر في النقر — الدقة تأتي من السرعة في المستويات الأعلى!",
    },
  },
  21: {
    objective: {
      en: "A color flashes — tap the matching color button as fast as possible!",
      es: "¡Un color parpadea — toca el botón del color correspondiente lo más rápido posible!",
      fr: "Une couleur clignote — tapez sur le bouton de couleur correspondant le plus vite possible !",
      de: "Eine Farbe blinkt — tippe so schnell wie möglich auf den passenden Farbbutton!",
      hu: "Egy szín felvillan — koppints a megfelelő szín gombra a lehető leggyorsabban!",
      ar: "يومض لون — انقر على زر اللون المطابق بأسرع ما يمكن!",
    },
    controls: {
      en: "Click the button whose color matches the big circle. Wrong taps lose points.",
      es: "Haz clic en el botón cuyo color coincida con el círculo grande. Los toques incorrectos restan puntos.",
      fr: "Cliquez sur le bouton dont la couleur correspond au grand cercle. Les mauvaises touches font perdre des points.",
      de: "Klicke auf den Button, dessen Farbe zum großen Kreis passt. Falsche Tipps kosten Punkte.",
      hu: "Kattints arra a gombra, amelynek színe megegyezik a nagy körrel. A rossz koppintások pontokat vonnak le.",
      ar: "انقر على الزر الذي يطابق لونه الدائرة الكبيرة. النقرات الخاطئة تخصم نقاطًا.",
    },
    tips: {
      en: "Don't overthink — trust your reflexes. Higher levels add more rounds!",
      es: "No lo pienses demasiado — confía en tus reflejos. ¡Los niveles altos añaden más rondas!",
      fr: "Ne réfléchissez pas trop — faites confiance à vos réflexes. Les niveaux supérieurs ajoutent plus de tours !",
      de: "Denk nicht zu viel — vertraue deinen Reflexen. Höhere Levels fügen mehr Runden hinzu!",
      hu: "Ne gondolkodj túl sokat — bízz a reflexeidben. A magasabb szintek több kört adnak hozzá!",
      ar: "لا تفكر كثيرًا — ثق بردود أفعالك. المستويات الأعلى تضيف جولات أكثر!",
    },
  },
  22: {
    objective: {
      en: "Green means GO (tap!), red means STOP (don't tap). Test your self-control!",
      es: "Verde significa ¡YA! (toca), rojo significa PARA (no toques). ¡Pon a prueba tu autocontrol!",
      fr: "Vert signifie GO (tapez !), rouge signifie STOP (ne tapez pas). Testez votre sang-froid !",
      de: "Grün bedeutet GO (tippen!), rot bedeutet STOP (nicht tippen). Teste deine Selbstbeherrschung!",
      hu: "A zöld jelent GO (koppints!), a piros jelent STOP (ne koppints). Teszteld az önuralmad!",
      ar: "الأخضر يعني انطلق (انقر!)، الأحمر يعني توقف (لا تنقر). اختبر ضبط النفس!",
    },
    controls: {
      en: "Tap only on green stimuli. Holding back on red scores bonus points.",
      es: "Toca solo los estímulos verdes. Contenerse en el rojo suma puntos extra.",
      fr: "Tapez uniquement sur les stimuli verts. Se retenir sur le rouge rapporte des points bonus.",
      de: "Tippe nur auf grüne Reize. Sich bei Rot zurückhalten gibt Bonuspunkte.",
      hu: "Csak a zöld ingerekre koppints. A pirosnál való visszafogás bónuszpontot ér.",
      ar: "انقر فقط على المحفزات الخضراء. الامتناع عن الأحمر يمنح نقاطًا إضافية.",
    },
    tips: {
      en: "Higher levels show more red and faster pace — stay disciplined!",
      es: "Los niveles altos muestran más rojo y ritmo más rápido — ¡mantente disciplinado!",
      fr: "Les niveaux supérieurs montrent plus de rouge et un rythme plus rapide — restez discipliné !",
      de: "Höhere Levels zeigen mehr Rot und schnelleres Tempo — bleib diszipliniert!",
      hu: "A magasabb szintek több pirosat és gyorsabb tempót mutatnak — maradj fegyelmezett!",
      ar: "المستويات الأعلى تظهر أحمر أكثر وإيقاعًا أسرع — ابقَ منضبطًا!",
    },
  },
  23: {
    objective: {
      en: "Cells light up briefly — memorize them, then tap the same cells!",
      es: "Las celdas se iluminan brevemente — ¡memorízalas y luego toca las mismas celdas!",
      fr: "Les cellules s'allument brièvement — mémorisez-les, puis tapez les mêmes cellules !",
      de: "Zellen leuchten kurz auf — merke sie dir, dann tippe dieselben Zellen!",
      hu: "A cellák röviden felgyulladnak — memorizáld őket, majd koppints ugyanazokra a cellákra!",
      ar: "تضيء الخلايا لفترة وجيزة — احفظها، ثم انقر على نفس الخلايا!",
    },
    controls: {
      en: "Watch the pattern, then click each cell that was lit. Wrong taps lose points.",
      es: "Observa el patrón, luego haz clic en cada celda iluminada. Los toques incorrectos restan puntos.",
      fr: "Observez le motif, puis cliquez sur chaque cellule allumée. Les mauvaises touches font perdre des points.",
      de: "Beobachte das Muster, dann klicke jede Zelle, die leuchtete. Falsche Tipps kosten Punkte.",
      hu: "Figyeld a mintát, majd kattints minden cellára, amely gyulladt. A rossz koppintások pontokat vonnak le.",
      ar: "راقب النمط، ثم انقر على كل خلية مضاءة. النقرات الخاطئة تخصم نقاطًا.",
    },
    tips: {
      en: "Chunk the lit cells into a shape in your mind. Bigger grids at higher levels!",
      es: "Agrupa las celdas iluminadas en una forma en tu mente. ¡Cuadrículas más grandes en niveles altos!",
      fr: "Regroupez les cellules allumées en une forme dans votre esprit. Grilles plus grandes aux niveaux supérieurs !",
      de: "Bündle die leuchtenden Zellen zu einer Form in deinem Kopf. Größere Raster bei höheren Levels!",
      hu: "Csoportosítsd a gyulladt cellákat egy alakká a fejedben. Nagyobb rácsok magasabb szinteken!",
      ar: "اجمع الخلايا المضاءة في شكل في عقلك. شبكات أكبر في المستويات الأعلى!",
    },
  },
  24: {
    objective: {
      en: "A sequence of shapes flashes — repeat them in the same order!",
      es: "Una secuencia de formas parpadea — ¡repítelas en el mismo orden!",
      fr: "Une séquence de formes clignote — répétez-les dans le même ordre !",
      de: "Eine Reihe von Formen blinkt — wiederhole sie in derselben Reihenfolge!",
      hu: "Egy alaksorozat felvillan — ismételd meg őket ugyanabban a sorrendben!",
      ar: "يومض تسلسل من الأشكال — كررها بنفس الترتيب!",
    },
    controls: {
      en: "Tap the shape buttons in the order they appeared. Mistakes restart the round.",
      es: "Toca los botones de formas en el orden en que aparecieron. Los errores reinician la ronda.",
      fr: "Tapez les boutons de forme dans l'ordre où ils sont apparus. Les erreurs redémarrent le tour.",
      de: "Tippe die Form-Buttons in der Reihenfolge, in der sie erschienen. Fehler starten die Runde neu.",
      hu: "Koppints az alakgombokra abban a sorrendben, ahogy megjelentek. A hibák újraindítják a kört.",
      ar: "انقر على أزرار الأشكال بالترتيب الذي ظهرت به. الأخطاء تعيد الجولة.",
    },
    tips: {
      en: "Say each shape silently as it appears. Longer sequences test your memory!",
      es: "Di cada forma en silencio al aparecer. ¡Las secuencias más largas ponen a prueba tu memoria!",
      fr: "Dites chaque forme silencieusement en l'apparaissant. Les séquences plus longues testent votre mémoire !",
      de: "Sage jede Form leise, wenn sie erscheint. Längere Sequenzen testen dein Gedächtnis!",
      hu: "Mondd csendben minden alakot, ahogy megjelenik. A hosszabb sorozatok tesztelik a memóriádat!",
      ar: "قل اسم كل شكل بصمت عند ظهوره. التسلسلات الأطول تختبر ذاكرتك!",
    },
  },
  25: {
    objective: {
      en: "Does the current shape match the one from N steps ago? Decide fast!",
      es: "¿La forma actual coincide con la de hace N pasos? ¡Decide rápido!",
      fr: "La forme actuelle correspond-elle à celle d'il y a N étapes ? Décidez vite !",
      de: "Entspricht die aktuelle Form der von vor N Schritten? Entscheide schnell!",
      hu: "Egyezik-e a jelenlegi alak a N lépéssel ezelőttivel? Dönts gyorsan!",
      ar: "هل الشكل الحالي يطابق الشكل من قبل N خطوات؟ قرر بسرعة!",
    },
    controls: {
      en: "Click YES if it matches the shape N steps back, NO if different.",
      es: "Haz clic en SÍ si coincide con la forma de hace N pasos, NO si es diferente.",
      fr: "Cliquez sur OUI si elle correspond à la forme d'il y a N étapes, NON si différente.",
      de: "Klicke JA, wenn sie zur Form von vor N Schritten passt, NEIN wenn anders.",
      hu: "Kattints az IGEN gombra, ha egyezik a N lépéssel ezelőtti alakkal, NEM-re, ha más.",
      ar: "انقر على نعم إذا كان يطابق الشكل من قبل N خطوات، لا إذا كان مختلفًا.",
    },
    tips: {
      en: "Keep a mental image of the last few shapes. Higher N = harder working memory!",
      es: "Mantén una imagen mental de las últimas formas. ¡N más alto = memoria de trabajo más difícil!",
      fr: "Gardez une image mentale des dernières formes. N plus élevé = mémoire de travail plus difficile !",
      de: "Behalte ein mentales Bild der letzten Formen. Höheres N = schwereres Arbeitsgedächtnis!",
      hu: "Tartsd meg az utolsó néhány alak mentális képét. Magasabb N = nehezebb munkamemória!",
      ar: "احتفظ بصورة ذهنية لآخر الأشكال القليلة. N أعلى = ذاكرة عاملة أصعب!",
    },
  },
  26: {
    objective: {
      en: "All shapes share a color — except one with a slightly different shade. Find it!",
      es: "Todas las formas comparten un color — excepto una con un tono ligeramente diferente. ¡Encuéntrala!",
      fr: "Toutes les formes partagent une couleur — sauf une avec une teinte légèrement différente. Trouvez-la !",
      de: "Alle Formen teilen eine Farbe — außer einer mit einem leicht anderen Ton. Finde sie!",
      hu: "Minden alak azonos színű — kivéve egy, amelyik egy kissé más árnyalatú. Keresd meg!",
      ar: "جميع الأشكال تتشارك لونًا — إلا واحدًا بظل مختلف قليلاً. ابحث عنه!",
    },
    controls: {
      en: "Click the shape with the different shade. Wrong taps lose points.",
      es: "Haz clic en la forma con el tono diferente. Los toques incorrectos restan puntos.",
      fr: "Cliquez sur la forme avec la teinte différente. Les mauvaises touches font perdre des points.",
      de: "Klicke auf die Form mit dem anderen Ton. Falsche Tipps kosten Punkte.",
      hu: "Kattints a más árnyalatú alakra. A rossz koppintások pontokat vonnak le.",
      ar: "انقر على الشكل بالظل المختلف. النقرات الخاطئة تخصم نقاطًا.",
    },
    tips: {
      en: "Look for subtle hue differences. Higher levels shrink the gap between shades!",
      es: "Busca diferencias sutiles de tono. ¡Los niveles altos reducen la diferencia entre tonos!",
      fr: "Cherchez des différences de teinte subtiles. Les niveaux supérieurs réduisent l'écart entre les teintes !",
      de: "Suche nach subtilen Farbtonunterschieden. Höhere Levels verkleinern den Abstand zwischen Tönen!",
      hu: "Keresd a finom árnyalatkülönbségeket. A magasabb szintek szűkítik a különbséget az árnyalatok között!",
      ar: "ابحث عن اختلافات دقيقة في درجة اللون. المستويات الأعلى تقلل الفجوة بين الدرجات!",
    },
  },
  27: {
    objective: {
      en: "All shapes are the same size — except one. Spot the different one!",
      es: "Todas las formas son del mismo tamaño — excepto una. ¡Encuentra la diferente!",
      fr: "Toutes les formes ont la même taille — sauf une. Repérez la différente !",
      de: "Alle Formen sind gleich groß — außer einer. Finde die andere!",
      hu: "Minden alak azonos méretű — kivéve egyet. Észre a különbözőt!",
      ar: "جميع الأشكال بنفس الحجم — إلا واحدًا. اكتشف المختلف!",
    },
    controls: {
      en: "Click the shape with a different size. Wrong taps lose points.",
      es: "Haz clic en la forma con un tamaño diferente. Los toques incorrectos restan puntos.",
      fr: "Cliquez sur la forme de taille différente. Les mauvaises touches font perdre des points.",
      de: "Klicke auf die Form mit anderer Größe. Falsche Tipps kosten Punkte.",
      hu: "Kattints a más méretű alakra. A rossz koppintások pontokat vonnak le.",
      ar: "انقر على الشكل بحجم مختلف. النقرات الخاطئة تخصم نقاطًا.",
    },
    tips: {
      en: "Size differences get subtler at higher levels — scan carefully!",
      es: "Las diferencias de tamaño son más sutiles en niveles altos — ¡escanea con cuidado!",
      fr: "Les différences de taille deviennent plus subtiles aux niveaux supérieurs — parcourez attentivement !",
      de: "Größenunterschiede werden bei höheren Levels subtiler — scanne sorgfältig!",
      hu: "A méretkülönbségek finomabbak lesznek magasabb szinteken — vizsgáld gondosan!",
      ar: "تصبح فروق الحجم أكثر دقة في المستويات الأعلى — امسح بعناية!",
    },
  },
  28: {
    objective: {
      en: "Two grids appear — find the ONE cell that differs between them!",
      es: "Aparecen dos cuadrículas — ¡encuentra la ÚNICA celda que difiere entre ellas!",
      fr: "Deux grilles apparaissent — trouvez l'UNIQUE cellule qui diffère entre elles !",
      de: "Zwei Raster erscheinen — finde die EINE Zelle, die sich unterscheidet!",
      hu: "Két rács jelenik meg — keresd meg az EGYETLEN cellát, amely különbözik köztük!",
      ar: "تظهر شبكتان — ابحث عن الخلية الوحيدة التي تختلف بينهما!",
    },
    controls: {
      en: "Click the differing cell in the bottom grid. Wrong taps lose points.",
      es: "Haz clic en la celda diferente de la cuadrícula inferior. Los toques incorrectos restan puntos.",
      fr: "Cliquez sur la cellule différente dans la grille du bas. Les mauvaises touches font perdre des points.",
      de: "Klicke auf die abweichende Zelle im unteren Raster. Falsche Tipps kosten Punkte.",
      hu: "Kattints az eltérő cellára az alsó rácsban. A rossz koppintások pontokat vonnak le.",
      ar: "انقر على الخلية المختلفة في الشبكة السفلية. النقرات الخاطئة تخصم نقاطًا.",
    },
    tips: {
      en: "Compare cell by cell systematically. Bigger grids and less time at higher levels!",
      es: "Compara celda por celda sistemáticamente. ¡Cuadrículas más grandes y menos tiempo en niveles altos!",
      fr: "Comparez cellule par cellule systématiquement. Grilles plus grandes et moins de temps aux niveaux supérieurs !",
      de: "Vergleiche Zelle für Zelle systematisch. Größere Raster und weniger Zeit bei höheren Levels!",
      hu: "Hasonlítsd össze celláról cellára szisztematikusan. Nagyobb rácsok és kevesebb idő magasabb szinteken!",
      ar: "قارن خلية بخلية بشكل منهجي. شبكات أكبر ووقت أقل في المستويات الأعلى!",
    },
  },
  29: {
    objective: {
      en: "A grid of numbers — tap the highest one as fast as you can!",
      es: "Una cuadrícula de números — ¡toca el más alto lo más rápido posible!",
      fr: "Une grille de nombres — tapez le plus élevé le plus vite possible !",
      de: "Ein Raster voller Zahlen — tippe die höchste so schnell du kannst!",
      hu: "Egy számokból álló rács — koppints a legmagasabbra a lehető leggyorsabban!",
      ar: "شبكة من الأرقام — انقر على الأعلى بأسرع ما يمكن!",
    },
    controls: {
      en: "Click the cell with the largest number. Wrong taps lose points.",
      es: "Haz clic en la celda con el número más grande. Los toques incorrectos restan puntos.",
      fr: "Cliquez sur la cellule avec le plus grand nombre. Les mauvaises touches font perdre des points.",
      de: "Klicke auf die Zelle mit der größten Zahl. Falsche Tipps kosten Punkte.",
      hu: "Kattints a legnagyobb számú cellára. A rossz koppintások pontokat vonnak le.",
      ar: "انقر على الخلية بالرقم الأكبر. النقرات الخاطئة تخصم نقاطًا.",
    },
    tips: {
      en: "Scan for double-digit numbers first. Bigger grids at higher levels!",
      es: "Busca primero los números de dos dígitos. ¡Cuadrículas más grandes en niveles altos!",
      fr: "Cherchez d'abord les nombres à deux chiffres. Grilles plus grandes aux niveaux supérieurs !",
      de: "Scanne zuerst nach zweistelligen Zahlen. Größere Raster bei höheren Levels!",
      hu: "Elsőként a kétjegyű számokat keresd. Nagyobb rácsok magasabb szinteken!",
      ar: "ابحث أولاً عن الأرقام المكونة من رقمين. شبكات أكبر في المستويات الأعلى!",
    },
  },
  30: {
    objective: {
      en: "Numbers are scattered — tap them in ascending order: 1, 2, 3...",
      es: "Los números están dispersos — toca en orden ascendente: 1, 2, 3...",
      fr: "Les nombres sont éparpillés — tapez-les dans l'ordre croissant : 1, 2, 3...",
      de: "Zahlen sind verstreut — tippe sie in aufsteigender Reihenfolge: 1, 2, 3...",
      hu: "A számok szétszórva vannak — koppints rájuk növekvő sorrendben: 1, 2, 3...",
      ar: "الأرقام متناثرة — انقر عليها بترتيب تصاعدي: 1، 2، 3...",
    },
    controls: {
      en: "Click numbers from lowest to highest. Wrong taps lose points.",
      es: "Haz clic en los números de menor a mayor. Los toques incorrectos restan puntos.",
      fr: "Cliquez sur les nombres du plus bas au plus élevé. Les mauvaises touches font perdre des points.",
      de: "Klicke Zahlen vom kleinsten zum größten. Falsche Tipps kosten Punkte.",
      hu: "Kattints a számokra a legkisebbtől a legnagyobbig. A rossz koppintások pontokat vonnak le.",
      ar: "انقر على الأرقام من الأصغر إلى الأكبر. النقرات الخاطئة تخصم نقاطًا.",
    },
    tips: {
      en: "Plan a path through the grid before tapping. More numbers at higher levels!",
      es: "Planifica un camino por la cuadrícula antes de tocar. ¡Más números en niveles altos!",
      fr: "Planifiez un chemin à travers la grille avant de taper. Plus de nombres aux niveaux supérieurs !",
      de: "Plane einen Pfad durch das Raster, bevor du tippst. Mehr Zahlen bei höheren Levels!",
      hu: "Tervezz egy utat a rácsban, mielőtt koppintasz. Több szám magasabb szinteken!",
      ar: "خطط مسارًا عبر الشبكة قبل النقر. أرقام أكثر في المستويات الأعلى!",
    },
  },
  31: {
    objective: {
      en: "Solve the arithmetic problem — pick the right answer fast!",
      es: "Resuelve el problema aritmético — ¡elige la respuesta correcta rápido!",
      fr: "Résolvez le problème arithmétique — choisissez la bonne réponse vite !",
      de: "Löse das Rechenaufgabe — wähle die richtige Antwort schnell!",
      hu: "Oldd meg a számtani feladatot — válaszd a helyes választ gyorsan!",
      ar: "حل المسألة الحسابية — اختر الإجابة الصحيحة بسرعة!",
    },
    controls: {
      en: "Click the button with the correct result. Wrong answers lose points.",
      es: "Haz clic en el botón con el resultado correcto. Las respuestas incorrectas restan puntos.",
      fr: "Cliquez sur le bouton avec le bon résultat. Les mauvaises réponses font perdre des points.",
      de: "Klicke auf den Button mit dem richtigen Ergebnis. Falsche Antworten kosten Punkte.",
      hu: "Kattints a gombra a helyes eredménnyel. A hibás válaszok pontokat vonnak le.",
      ar: "انقر على الزر بالنتيجة الصحيحة. الإجابات الخاطئة تخصم نقاطًا.",
    },
    tips: {
      en: "Higher levels add multiplication and tighter timers — calculate quickly!",
      es: "Los niveles altos añaden multiplicación y menos tiempo — ¡calcula rápido!",
      fr: "Les niveaux supérieurs ajoutent la multiplication et des chronos plus serrés — calculez vite !",
      de: "Höhere Levels fügen Multiplikation und knappere Timer hinzu — rechne schnell!",
      hu: "A magasabb szintek szorzást és szorosabb időzítőket adnak hozzá — számolj gyorsan!",
      ar: "المستويات الأعلى تضيف الضرب ومؤقتات أضيق — احسب بسرعة!",
    },
  },
  32: {
    objective: {
      en: "Is the second number higher or lower than the first? Guess fast!",
      es: "¿El segundo número es mayor o menor que el primero? ¡Adivina rápido!",
      fr: "Le deuxième nombre est-il plus élevé ou plus bas que le premier ? Devinez vite !",
      de: "Ist die zweite Zahl höher oder niedriger als die erste? Rate schnell!",
      hu: "A második szám magasabb vagy alacsonyabb, mint az első? Tippelj gyorsan!",
      ar: "هل الرقم الثاني أعلى أم أقل من الأول؟ خمن بسرعة!",
    },
    controls: {
      en: "Click Higher or Lower after seeing the first number.",
      es: "Haz clic en Mayor o Menor tras ver el primer número.",
      fr: "Cliquez sur Plus élevé ou Plus bas après avoir vu le premier nombre.",
      de: "Klicke Höher oder Niedriger, nachdem du die erste Zahl gesehen hast.",
      hu: "Kattints a Magasabb vagy Alacsonyabb gombra az első szám látása után.",
      ar: "انقر على أعلى أو أقل بعد رؤية الرقم الأول.",
    },
    tips: {
      en: "It's pure probability near 50 — trust your gut and react quickly!",
      es: "Es pura probabilidad cerca del 50 — ¡confía en tu instinto y reacciona rápido!",
      fr: "C'est de la probabilité pure près de 50 — faites-vous confiance et réagissez vite !",
      de: "Es ist reine Wahrscheinlichkeit nahe 50 — vertraue deinem Bauchgefühl und reagiere schnell!",
      hu: "Ez tiszta valószínűség az 50 körül — bízz az megérzésedben és reagálj gyorsan!",
      ar: "إنها احتمالية خالصة قرب 50 — ثق بحدسك وتفاعل بسرعة!",
    },
  },
  33: {
    objective: {
      en: "A number sequence has one missing — figure out the pattern and pick it!",
      es: "Una secuencia numérica tiene un número ausente — ¡averigua el patrón y elige!",
      fr: "Une séquence de nombres a un manquant — déterminez le motif et choisissez-le !",
      de: "Eine Zahlenreihe hat eine fehlende Zahl — erkenne das Muster und wähle sie!",
      hu: "Egy számsorozatból hiányzik egy szám — találd ki a mintát és válaszd ki!",
      ar: "تسلسل أرقام ينقصه رقم — اكتشف النمط واختره!",
    },
    controls: {
      en: "Click the button with the missing number. Wrong answers lose points.",
      es: "Haz clic en el botón con el número ausente. Las respuestas incorrectas restan puntos.",
      fr: "Cliquez sur le bouton avec le nombre manquant. Les mauvaises réponses font perdre des points.",
      de: "Klicke auf den Button mit der fehlenden Zahl. Falsche Antworten kosten Punkte.",
      hu: "Kattints a gombra a hiányzó számmal. A hibás válaszok pontokat vonnak le.",
      ar: "انقر على الزر بالرقم المفقود. الإجابات الخاطئة تخصم نقاطًا.",
    },
    tips: {
      en: "Look for the step between numbers. Bigger steps at higher levels!",
      es: "Busca el paso entre los números. ¡Pasos más grandes en niveles altos!",
      fr: "Cherchez le pas entre les nombres. Pas plus grands aux niveaux supérieurs !",
      de: "Suche nach der Schrittweite zwischen den Zahlen. Größere Schritte bei höheren Levels!",
      hu: "Keresd a lépések nagyságát a számok között. Nagyobb lépések magasabb szinteken!",
      ar: "ابحث عن الخطوة بين الأرقام. خطوات أكبر في المستويات الأعلى!",
    },
  },
  34: {
    objective: {
      en: "A number appears — is it even or odd? Decide fast!",
      es: "Aparece un número — ¿es par o impar? ¡Decide rápido!",
      fr: "Un nombre apparaît — est-il pair ou impair ? Décidez vite !",
      de: "Eine Zahl erscheint — ist sie gerade oder ungerade? Entscheide schnell!",
      hu: "Egy szám megjelenik — páros vagy páratlan? Dönts gyorsan!",
      ar: "يظهر رقم — هل هو زوجي أم فردي؟ قرر بسرعة!",
    },
    controls: {
      en: "Click EVEN or ODD. Wrong answers lose points.",
      es: "Haz clic en PAR o IMPAR. Las respuestas incorrectas restan puntos.",
      fr: "Cliquez sur PAIR ou IMPAIR. Les mauvaises réponses font perdre des points.",
      de: "Klicke GERADE oder UNGERADE. Falsche Antworten kosten Punkte.",
      hu: "Kattints a Páros vagy Páratlan gombra. A hibás válaszok pontokat vonnak le.",
      ar: "انقر على زوجي أو فردي. الإجابات الخاطئة تخصم نقاطًا.",
    },
    tips: {
      en: "Check the last digit — if it's 0,2,4,6,8 it's even. Bigger numbers at higher levels!",
      es: "Revisa el último dígito — si es 0,2,4,6,8 es par. ¡Números más grandes en niveles altos!",
      fr: "Vérifiez le dernier chiffre — si c'est 0,2,4,6,8 c'est pair. Nombres plus grands aux niveaux supérieurs !",
      de: "Prüfe die letzte Ziffer — bei 0,2,4,6,8 ist sie gerade. Größere Zahlen bei höheren Levels!",
      hu: "Ellenőrizd az utolsó számjegyet — ha 0,2,4,6,8 akkor páros. Nagyobb számok magasabb szinteken!",
      ar: "تحقق من الرقم الأخير — إذا كان 0،2،4،6،8 فهو زوجي. أرقام أكبر في المستويات الأعلى!",
    },
  },
  35: {
    objective: {
      en: "A shape appears — tap the bin matching its color!",
      es: "Aparece una forma — ¡toca el contenedor que coincida con su color!",
      fr: "Une forme apparaît — tapez le bac correspondant à sa couleur !",
      de: "Eine Form erscheint — tippe auf das Fach, das zu ihrer Farbe passt!",
      hu: "Egy alak jelenik meg — koppints a színének megfelelő tárolóra!",
      ar: "يظهر شكل — انقر على الحاوية المطابقة للونه!",
    },
    controls: {
      en: "Click the color button that matches the shape's color. Wrong taps lose points.",
      es: "Haz clic en el botón de color que coincida con el color de la forma. Los toques incorrectos restan puntos.",
      fr: "Cliquez sur le bouton de couleur correspondant à la couleur de la forme. Les mauvaises touches font perdre des points.",
      de: "Klicke den Farbbutton, der zur Farbe der Form passt. Falsche Tipps kosten Punkte.",
      hu: "Kattints arra a színgombra, amely megegyezik az alak színével. A rossz koppintások pontokat vonnak le.",
      ar: "انقر على زر اللون الذي يطابق لون الشكل. النقرات الخاطئة تخصم نقاطًا.",
    },
    tips: {
      en: "Focus on the color, not the shape. Faster pace at higher levels!",
      es: "Concéntrate en el color, no en la forma. ¡Ritmo más rápido en niveles altos!",
      fr: "Concentrez-vous sur la couleur, pas la forme. Rythme plus rapide aux niveaux supérieurs !",
      de: "Konzentriere dich auf die Farbe, nicht die Form. Schnelleres Tempo bei höheren Levels!",
      hu: "A színre koncentrálj, nem az alakra. Gyorsabb tempó magasabb szinteken!",
      ar: "ركز على اللون، وليس الشكل. إيقاع أسرع في المستويات الأعلى!",
    },
  },
  36: {
    objective: {
      en: "A target shape is shown — find the matching shape (ignore the colors)!",
      es: "Se muestra una forma objetivo — ¡encuentra la forma coincidente (ignora los colores)!",
      fr: "Une forme cible est affichée — trouvez la forme correspondante (ignorez les couleurs) !",
      de: "Eine Zielform wird gezeigt — finde die passende Form (ignoriere die Farben)!",
      hu: "Egy célalak jelenik meg — keresd meg az egyező alakot (ne figyeld a színeket)!",
      ar: "يظهر شكل مستهدف — ابحث عن الشكل المطابق (تجاهل الألوان)!",
    },
    controls: {
      en: "Click the option with the same SHAPE as the target. Wrong taps lose points.",
      es: "Haz clic en la opción con la misma FORMA que el objetivo. Los toques incorrectos restan puntos.",
      fr: "Cliquez sur l'option avec la même FORME que la cible. Les mauvaises touches font perdre des points.",
      de: "Klicke auf die Option mit derselben FORM wie das Ziel. Falsche Tipps kosten Punkte.",
      hu: "Kattints arra az opcióra, amelynek ALAKJA megegyezik a céllal. A rossz koppintások pontokat vonnak le.",
      ar: "انقر على الخيار بنفس الشكل كالهدف. النقرات الخاطئة تخصم نقاطًا.",
    },
    tips: {
      en: "Colors are distractions — focus only on the shape. Faster pace at higher levels!",
      es: "Los colores son distracciones — concéntrate solo en la forma. ¡Ritmo más rápido en niveles altos!",
      fr: "Les couleurs sont des distractions — concentrez-vous uniquement sur la forme. Rythme plus rapide aux niveaux supérieurs !",
      de: "Farben sind Ablenkungen — konzentriere dich nur auf die Form. Schnelleres Tempo bei höheren Levels!",
      hu: "A színek figyelemelterelők — csak az alakra koncentrálj. Gyorsabb tempó magasabb szinteken!",
      ar: "الألوان مشتتات — ركز فقط على الشكل. إيقاع أسرع في المستويات الأعلى!",
    },
  },
};

export const getTutorialText = (gameId, stepKey) => {
  const lang = getLanguage();
  const step = tutorialContent[gameId]?.[stepKey];
  return step?.[lang] || step?.en || '';
};